version: '2'

services:
  server:
    build: .
    image: amdirent/cliq-pic:0.0.63
    network_mode: 'host'
    env_file: docker-compose.env
    ports:
      - '30.0.6300'

  sidekiq:
    build: .
    image: amdirent/cliq-pic:0.0.63
    network_mode: 'host'
    env_file: docker-compose.env
    command: [bundle, exec, sidekiq]
