# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  forest_env_secret: 26ed6b07f487710b8d4065174f47fab47f72dbd8c0bfb03fd4ca2b5d1a4824ef
  forest_auth_secret: UfgcDM39vAt40mVStlt36A
  secret_key_base: 10064e54e54b6e47f985c90d9216c7399702158e273f68c6bae68cfa21edb0bc1a93447a26e23743f0d76deaec96d59e91c87caa4a730e7561edc016df942440

test:
  secret_key_base: 8ec7485a9e1ca7aaa997b40512319a2bc9374ae1be85a91e477c8dcd09dfc49f83264cbfc1b911ff7dfef5c0993b001a5610655707feb81f5080621c0913ae82

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  forest_env_secret: <%= ENV["FOREST_ENV_SECRET"] %>
  forest_auth_secret: <%= ENV["FOREST_AUTH_SECRET"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
